/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ca-central-1",
    "aws_appsync_graphqlEndpoint": "https://iw33a5eyozgktiieqeezrlbtgi.appsync-api.ca-central-1.amazonaws.com/graphql",
    "aws_appsync_region": "ca-central-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-b4ik23fmcvagxk2ck5c3m5ohvi",
    "aws_cognito_identity_pool_id": "ca-central-1:87d168bc-364b-4f96-9fbc-3ae86d5af4a5",
    "aws_cognito_region": "ca-central-1",
    "aws_user_pools_id": "ca-central-1_REc3FpHqm",
    "aws_user_pools_web_client_id": "6a6pqrj1evsolekb4gajcumdro",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "webegginere2298be3ece246e4a060d5e0e10de1e5225639-dev",
    "aws_user_files_s3_bucket_region": "ca-central-1"
};


export default awsmobile;
